# Configuration file
# https://github.com/connection-lost/LockettePro/wiki/*-config.yml
# If there are missing entries, you can add them manually.

language-file-name: 'lang.yml'
enable-quick-protect: true
enable-uuid-support: false
block-interfere-placement: true
block-item-transfer-in: false
block-item-transfer-out: true
block-hopper-minecart: remove
cache-time-seconds: 0
private-signs:
- '[Private]'
- '[private]'
additional-signs:
- '[More Users]'
- '[more users]'
everyone-signs:
- '[Everyone]'
- '[everyone]'
timer-signs:
- '[Timer:@]'
- '[timer:@]'
lockables:
- CHEST
- TRAPPED_CHEST
- FURNACE
- BURNING_FURNACE
- HOPPER
- BREWING_STAND
- DIAMOND_BLOCK
- WOODEN_DOOR
- SPRUCE_DOOR
- BIRCH_DOOR
- JUNGLE_DOOR
- ACACIA_DOOR
- DARK_OAK_DOOR
- IRON_DOOR_BLOCK